Update master_clsgbookingsdb.yml

diff --git a/.github/workflows/master_clsgbookingsdb.yml b/.github/workflows/master_clsgbookingsdb.yml
--- a/.github/workflows/master_clsgbookingsdb.yml
+++ b/.github/workflows/master_clsgbookingsdb.yml
@@ -39,12 +39,10 @@ jobs:
           USER: ${{ secrets.USER }}
           PASS: ${{ secrets.PASS }}
           FRONTEND_URLC: ${{ secrets.FRONTEND_URLC }}
-
         run: |
           cd backend
           echo "Creating .env file..."
           cat <<EOF > .env
-
           FRONTEND_URL=${FRONTEND_URL}
           FRONTEND_URLC=${FRONTEND_URLC}
           PASS=${PASS}
@@ -76,12 +74,16 @@ jobs:
           echo "Verifying start script in package.json..."
           cat package.json | grep '"start":'
 
+      # Prepare deployment artifact
       - name: Create deployment artifact
         run: |
           cd backend
-          npm install --production # Ensure production dependencies are installed
-          zip -r node-app.zip node-app # Package the 'node-app' directory (not the entire backend)
-      
+          if [ -d "node-app" ]; then
+            zip -r node-app.zip node-app
+          else
+            echo "node-app directory does not exist."
+            exit 1  # Fail if node-app directory is not found
+          fi
 
       # Debug deployment artifact creation
       - name: Debug deployment artifact
@@ -125,10 +127,8 @@ jobs:
       # Ensure server.js is readable and executable
       - name: Ensure server.js permissions
         run: |
-          chmod +rx app/server.js
-          ls -la app
-
-
+          chmod +rx app/node-app/server.js
+          ls -la app/node-app
 
       # Deploy to Azure Web App using the publish profile
       - name: Deploy to Azure Web App
@@ -137,7 +137,6 @@ jobs:
           app-name: 'CLSGBookingsDB'
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILEDB }}
           package: ./node-app.zip
-
 
       # Debug deployment logs
       - name: Debug deployment logs
